version: '2.1'
services:
  localstack:
    image: localstack/localstack
    ports:
      - '4567-4584:4567-4584'
      - '${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}'
    environment:
      - SERVICES=${SERVICES-serverless}
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR-/tmp/localstack/data}
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION- }
      - DYNAMODB_TABLE=${DYNAMODB_TABLE- }
    volumes:
      - ./.localstack:/tmp/localstack
