= README
:toc:

== Start Here

Here's the `TL;DR` summary:

[source,bash]
----
git clone --recurse-submodules git@github.com:ripcitysoftware/product-service.git
cd product-service
./run.sh -abo
----

That's it!

== Checkout

In order to checkout this project, with it's submodules, you'll need to use the `git` option `--recurse-submodules`:

[source,bash]
----
git clone --recurse-submodules git@github.com:ripcitysoftware/product-service.git
----

== Run DB only

To run the database and it's migrations, or just the migrations (assuming the DB is already running) use this command from the root dir (or `./run.sh -p):

[NOTE]
====
We need to adjust the value of `LIQUIBASE_PATH` to point `./` instead of `src/main/liquibase`.
====

[source,bash]
----
LIQUIBASE_PATH=./ docker-compose -f ./src/main/liquibase/docker-compose.yml up -d
----

== Run Everything

If you want to run the application and the database use this command (or `./run.sh -a`):

[source,bash]
----
docker-compose -f docker-compose.build.yml -f ./src/main/liquibase/docker-compose.yml -f up -d
----

== Helpful Docker Commands

Here are a few useful `docker` aliases. These aliases are a good alternative to `docker ps -a` and `docker ps`, they provide useful output that fits better on your terminal.

[source,bash]
----
alias dpta='docker ps --all --format "table {{.Image}}\t{{.Status}}\t{{.Ports}}\t{{.Names}}"' # <1>
alias dpt='docker ps --format "table {{.Image}}\t{{.Status}}\t{{.Ports}}\t{{.Names}}"' # <2>
----
<1> All running and stopped docker containers.

<2> All running containers.

== Test Data

For test data, consider using a data generation tool like https://mockaroo.com[mackaroo].
