--
-- PRODUCT
--
DROP TABLE IF EXISTS PRODUCT;

DROP SEQUENCE IF EXISTS PRODUCT_ID_SEQ;

CREATE SEQUENCE PRODUCT_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE TABLE PRODUCT (
     PRODUCT_ID               BIGINT                   NOT NULL DEFAULT NEXTVAL('PRODUCT_ID_SEQ') PRIMARY KEY,
     GTIN                     CHARACTER VARYING(14),
     COMPANY_NAME             CHARACTER VARYING(70),
     BRAND                    CHARACTER VARYING(70),
     LABEL_DESCRIPTION        CHARACTER VARYING(500),
     MEDIUM_IMAGE_URL         CHARACTER VARYING(2500),
     VENDOR                   CHARACTER VARYING(200),
     LANGUAGE_CODE            CHARACTER VARYING(2),
     DATE_REGISTERED          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
     DATE_UPDATED             TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);


ALTER SEQUENCE PRODUCT_ID_SEQ OWNED BY PRODUCT.PRODUCT_ID;

COMMENT ON TABLE PRODUCT IS 'REPRESENTS A PRODUCT.';
COMMENT ON COLUMN PRODUCT.PRODUCT_ID IS 'PRODUCT ID, PRIMARY KEY';
COMMENT ON COLUMN PRODUCT.GTIN IS 'PRODUCT BARCODE/UPC';
COMMENT ON COLUMN PRODUCT.COMPANY_NAME IS 'THE NAME OF THIS PRODUCT';
COMMENT ON COLUMN PRODUCT.BRAND IS 'COMPANY BRAND THAT MAKES THIS PRODUCT';
COMMENT ON COLUMN PRODUCT.LABEL_DESCRIPTION IS 'LABEL DESCRIPTION OR THE PRODUCT';
COMMENT ON COLUMN PRODUCT.MEDIUM_IMAGE_URL IS 'URL TO A MEDIUM SIZED IMAGE OF THE PRODUCT';
COMMENT ON COLUMN PRODUCT.VENDOR IS 'COMPANY NAME';
COMMENT ON COLUMN PRODUCT.LANGUAGE_CODE IS 'LANGUAGE CODE';
COMMENT ON COLUMN PRODUCT.DATE_REGISTERED IS 'THE TIMESTAMP WHEN A PRODUCT ROW IS CREATED';
COMMENT ON COLUMN PRODUCT.DATE_UPDATED IS 'THE LAST TIME THIS ROW WAS UPDATED';
